/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import javax.swing.JOptionPane;
import model.RealEstateUser;
import network.RemoteNodeInterface;

/**
 *
 * @author IPT
 */
public class MyService extends javax.swing.JFrame {
    
    // Variáveis para guardar a sessão
    private RemoteNodeInterface node;
    private RealEstateUser myUser;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyService.class.getName());
    
    /**
     * Construtor Obrigatório para o Login funcionar
     */
    public MyService(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        
        initComponents(); // Inicia o design gráfico
        
        // Configurações extra
        this.setLocationRelativeTo(null);
        this.setTitle("Dashboard - Utilizador: " + (user != null ? user.getUserName() : "Desconhecido"));
        
        if (user != null) {
            lblWelcome.setText("Bem vindo, " + user.getUserName());
        }
    }

    /**
     * Construtor vazio (necessário para o editor gráfico do NetBeans não dar erro)
     * Não deve ser usado pelo Login
     */
    public MyService() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNodeAddress = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        btRegisterProp = new javax.swing.JButton();
        btViewMyAssets = new javax.swing.JButton();
        btTenantArea = new javax.swing.JButton();
        btMarket = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtNodeAddress.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtNodeAddress.setText("//10.10.208.35:10010/remoteP2P");
        txtNodeAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote Object Address"));
        txtNodeAddress.addActionListener(this::txtNodeAddressActionPerformed);
        txtNodeAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNodeAddressKeyPressed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setText("Bem vindo, @user ");

        btRegisterProp.setText("Registar propriedade");
        btRegisterProp.addActionListener(this::btRegisterPropActionPerformed);

        btViewMyAssets.setText("Ver Minhas Propriedades");
        btViewMyAssets.addActionListener(this::btViewMyAssetsActionPerformed);

        btTenantArea.setText("Área de Inquilino");
        btTenantArea.addActionListener(this::btTenantAreaActionPerformed);

        btMarket.setText("Mercado Imobiliário");
        btMarket.addActionListener(this::btMarketActionPerformed);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/logo-rwa.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtNodeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btRegisterProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMarket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTenantArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btViewMyAssets, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRegisterProp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btViewMyAssets, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTenantArea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(logo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(txtNodeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNodeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodeAddressActionPerformed

    private void txtNodeAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNodeAddressKeyPressed
       
    }//GEN-LAST:event_txtNodeAddressKeyPressed

    private void btRegisterPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterPropActionPerformed
        if (node == null || myUser == null) {
            JOptionPane.showMessageDialog(this, "Erro de conexão ou sessão inválida.");
            return;
        }
        
        // Abre a janela de registo passando as credenciais
        RegisterPropertyGUI regWin = new RegisterPropertyGUI(node, myUser);
        regWin.setVisible(true);
    }//GEN-LAST:event_btRegisterPropActionPerformed

    private void btTenantAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTenantAreaActionPerformed
        // TODO add your handling code here:
        if (node != null) {
            new TenantContractsGUI(node, myUser).setVisible(true);
        }
    }//GEN-LAST:event_btTenantAreaActionPerformed

    private void btViewMyAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewMyAssetsActionPerformed
        // TODO add your handling code here:
        if (node != null && myUser != null) {
            new MyPropertiesGUI(node, myUser).setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Sessão inválida.");
        }
    }//GEN-LAST:event_btViewMyAssetsActionPerformed

    private void btMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMarketActionPerformed
        // TODO add your handling code here:
        if (node != null) {
            // Abre a janela do Mercado passando a conexão e o utilizador atual
            new MarketplaceGUI(node, myUser).setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: Sem conexão ao servidor.");
        }
    }//GEN-LAST:event_btMarketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMarket;
    private javax.swing.JButton btRegisterProp;
    private javax.swing.JButton btTenantArea;
    private javax.swing.JButton btViewMyAssets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField txtNodeAddress;
    // End of variables declaration//GEN-END:variables
}
