/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.RealEstateProperty;
import model.RealEstateUser;
import model.transaction.RealEstateTransaction;
import network.RemoteNodeInterface;

/**
 *
 * @author Tiago Paiva
 * @author Pedro Laúdo
 */
public class RegisterPropertyGUI extends javax.swing.JFrame {

    // Referência para o nó da blockchain (Miner)
    RemoteNodeInterface node;
    RealEstateUser myUser;
    
    /**
     * Creates new form RegisterPropertyGUI
     */
    public RegisterPropertyGUI(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        
        initComponents(); // Método obrigatório do NetBeans
        
        // As minhas configurações
        setLocationRelativeTo(null); // Centrar janela
        
        if (myUser != null) {
            lblUser.setText("Registante: " + myUser.getUserName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAddress = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(466, 360));
        setResizable(false);

        txtAddress.setText("Rua de Tomar");
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtArea.setText("95");
        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        txtValue.setText("120000");

        txtType.setText("T3");
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        btRegister.setText("Registar Imóvel");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        jLabel1.setText("Morada");

        jLabel2.setText("Tipo de imóvel: ");

        jLabel3.setText("Área (m2)");

        jLabel4.setText("Preço");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(73, 73, 73)
                                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAddress))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(51, 51, 51)
                                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btRegister)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btRegister)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(822, 50));

        btClose.setText("Fechar");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        lblUser.setText("Utilizador : ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/logo-rwa-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addGap(122, 122, 122)
                .addComponent(btClose)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClose)
                    .addComponent(lblUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        try {
            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // :: 1. VALIDAÇÃO DE DADOS
            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // Verifica se o utilizador deixou algum campo em branco na interface
            if (txtAddress.getText().isEmpty() || txtType.getText().isEmpty() || 
                txtArea.getText().isEmpty() || txtValue.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
                return;
            }

            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // :: 2. CONVERSÃO E LEITURA
            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // Tenta converter o texto das caixas para números.
            // Se o utilizador escrever letras, o código salta para o 'catch (NumberFormatException)'
            double size = Double.parseDouble(txtArea.getText());
            double value = Double.parseDouble(txtValue.getText());
            String address = txtAddress.getText();
            String type = txtType.getText();

            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // :: 3. CRIAÇÃO DO ATIVO (RWA)
            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // Instancia o objeto Java. O construtor calcula automaticamente o Hash (ID)
            // baseado na morada e tipo, garantindo unicidade.
            RealEstateProperty prop = new RealEstateProperty(address, type, size, value);
            
            // --- ESTRATÉGIA DE ARMAZENAMENTO DE METADADOS ---
            // Como a blockchain guarda transações e não bases de dados relacionais,
            // concatenamos as informações vitais (ID, Tipo e Morada) numa única String.
            // Exemplo de resultado: "RWA-A1b2C3d4:Apartamento T3:Rua Principal, Lisboa"
            // Isto permite que, ao ler a blockchain no futuro, saibamos os detalhes sem bases de dados externas.
            String fullDescription = prop.getUniqueBlockchainID() + ":" + type + ":" + address;
            
            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // :: 4. CRIAÇÃO DA TRANSAÇÃO (MINTING)
            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // Criamos a transação "Génesis" deste imóvel.
            // O utilizador envia 1000 tokens (representando 100% da propriedade) para si próprio.
            RealEstateTransaction tx = new RealEstateTransaction(
                myUser,                 // Quem cria (Dono original)
                myUser.getUserName(),   // Quem recebe (O próprio, pois é o registo inicial)
                fullDescription,        // O identificador composto com os metadados
                1000                    // Quantidade inicial de tokens (fracionamento)
            );

            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // :: 5. ENVIO PELA REDE P2P
            // :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            if (node != null) {
                // Serializa o objeto Transação para Base64 (texto) e envia para a rede
                node.addTransaction(utils.Utils.ObjectToBase64(tx));
                
                // Feedback de sucesso ao utilizador
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Imóvel Registado com Sucesso!\n" +
                    "Aguarde a mineração do bloco para ver na sua carteira.\n\n" +
                    "ID Gerado: " + fullDescription);
                
                this.dispose(); // Fecha a janela de registo
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro: Sem conexão ao servidor P2P.");
            }

        } catch (NumberFormatException e) {
            // Tratamento específico para quando o utilizador escreve texto nos campos numéricos
            javax.swing.JOptionPane.showMessageDialog(this, "Erro de Formato: Área e Valor têm de ser números (use ponto '.' para decimais).");
        } catch (Exception e) {
            // Tratamento de erros genéricos (ex: falha na criptografia, erro de rede)
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao registar: " + e.getMessage());
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btRegisterActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
