/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain06_RealEstate;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Tiago Paiva
 */
public class FilterGUI extends javax.swing.JFrame {

    private RemoteNodeInterface node;

    /**
     * Construtor que recebe o nó para aceder à Blockchain
     */
    public FilterGUI(RemoteNodeInterface node) {
        this.node = node;
        initComponents();
        this.setTitle("Filtrar Transações");
        this.setLocationRelativeTo(null); // Centrar no ecrã
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); // Fecha só esta janela
        
        // Carrega tudo ao abrir
        atualizarLista("");
    }

    // Método principal de filtragem
    private void atualizarLista(String textoFiltro) {
        DefaultListModel model = new DefaultListModel();
        textoFiltro = textoFiltro.toLowerCase().trim();

        try {
            // CORREÇÃO AQUI: Usar .getBlocks() em vez de .getChain()
            List<Block> listaBlocos = node.getBlockchain().getBlocks();

            for (Block b : listaBlocos) {
                // Algumas implementações guardam uma lista de dados, outras um objeto único
                // Vamos assumir que 'getData()' devolve algo que podemos verificar
                Object dados = b.getData(); 
                
                // Se os dados forem uma lista (comum neste projeto), iteramos sobre ela
                if (dados instanceof List) {
                    for (Object obj : (List) dados) {
                        verificarEAdicionar(model, obj, textoFiltro);
                    }
                } else {
                    // Se for um objeto único
                    verificarEAdicionar(model, dados, textoFiltro);
                }
            }
        } catch (Exception e) {
            model.addElement("Erro ao ler blockchain: " + e.getMessage());
        }
        lstResultados.setModel(model);
    }

    private void verificarEAdicionar(DefaultListModel model, Object dados, String textoFiltro) {
        if (dados instanceof RealEstateTransaction) {
            RealEstateTransaction tx = (RealEstateTransaction) dados;
            
            // Constrói uma string com os campos importantes para pesquisa
            String conteudoParaPesquisa = 
                  (tx.getAssetName() + " " +    
                   tx.getTxtSender() + " " +    
                   tx.getTxtReceiver()          
                  ).toLowerCase();

            // Se filtro vazio OU encontrou texto
            if (textoFiltro.isEmpty() || conteudoParaPesquisa.contains(textoFiltro)) {
                model.addElement(tx.toString());
            }
        } else if (dados != null) {
            // Fallback para dados genéricos (ex: String "Genesis Block")
            if (textoFiltro.isEmpty() || dados.toString().toLowerCase().contains(textoFiltro)) {
                model.addElement(dados.toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResultados = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPesquisa.setText("jTextField1");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        lstResultados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstResultados);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:
        atualizarLista(txtPesquisa.getText());
    }//GEN-LAST:event_txtPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstResultados;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
