/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain06_RealEstate;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Utils;

/**
 *
 * @author Tiago Paiva
 */
public class MarketplaceGUI extends javax.swing.JFrame {

    private RemoteNodeInterface node;
    private RealEstateUser myUser;
    private DefaultTableModel model;
    
    // Lista para guardar as propostas em memória e saber qual é qual ao clicar na tabela
    private List<SaleProposal> displayedProposals = new ArrayList<>();

    public MarketplaceGUI(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Mercado Imobiliário - " + user.getUserName());
        
        model = (DefaultTableModel) tblMarket.getModel();
        model.setColumnIdentifiers(new String[]{"ID Imóvel", "Tipo", "De (User)", "Para", "Preço (€)"});
        
        loadMarket();
    }

    private void loadMarket() {
        model.setRowCount(0);
        displayedProposals.clear();
        
        if (node == null) return;
        try {
            BlockChain bc = node.getBlockchain();
            HashSet<String> acceptedIDs = new HashSet<>();
            List<SaleProposal> allProposals = new ArrayList<>();

            // 1. Ler Blockchain
            for (Block b : bc.getBlocks()) {
                List transactions = b.getTransactions();
                if (transactions == null) continue;
                for (Object raw : transactions) {
                    try {
                        Object obj = raw;
                        if (raw instanceof String) {
                             byte[] data = java.util.Base64.getDecoder().decode((String) raw);
                             try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(new java.io.ByteArrayInputStream(data))) {
                                 obj = ois.readObject();
                             }
                        }
                        
                        if (obj instanceof SaleProposal) {
                            allProposals.add((SaleProposal) obj);
                        }
                        if (obj instanceof SaleAcceptance) {
                            acceptedIDs.add(((SaleAcceptance) obj).getProposalID());
                        }
                    } catch (Exception e) {}
                }
            }

            // 2. Filtrar e Mostrar
            for (SaleProposal p : allProposals) {
                // Se já foi aceite, não mostra
                if (acceptedIDs.contains(p.getProposalID())) continue;

                // LOGICA DE VISIBILIDADE:
                // Mostro se for PUBLICO ("MERCADO") ou se for especificamente para MIM
                // Também mostro as minhas próprias propostas para eu saber que estão ativas
                boolean isPublic = p.getTargetUser().equals("MERCADO");
                boolean isForMe = p.getTargetUser().equals(myUser.getUserName());
                boolean isMine = p.getProposer().equals(myUser.getUserName());

                if (isPublic || isForMe || isMine) {
                    displayedProposals.add(p);
                    model.addRow(new Object[]{
                        p.getPropertyID(),
                        p.getTokenAmount(),
                        p.getType(),
                        p.getProposer(),
                        p.getTargetUser(),
                        p.getPrice()
                    });
                }
            }

        } catch (Exception e) { e.printStackTrace(); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarket = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btCreateProposal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMarket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Imóvel", "Qtd Tokens", "Tipo Proposta", "De", "Para", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tblMarket);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(630, 50));

        btCreateProposal.setText("Vender/Comprar Imóvel");
        btCreateProposal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateProposalActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");

        btAccept.setText("Aceitar Negócio");
        btAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(btAccept)
                .addGap(18, 18, 18)
                .addComponent(btCreateProposal)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreateProposal)
                    .addComponent(jButton2)
                    .addComponent(btAccept))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        // TODO add your handling code here:
        int row = tblMarket.getSelectedRow();
        if (row == -1) return;

        SaleProposal selectedProposal = displayedProposals.get(row);

        // Não posso aceitar a minha própria proposta
        if (selectedProposal.getProposer().equals(myUser.getUserName())) {
            JOptionPane.showMessageDialog(this, "Não pode aceitar a sua própria proposta.");
            return;
        }

        try {
            int confirm = JOptionPane.showConfirmDialog(this, "Tem a certeza que quer aceitar este negócio?");
            if (confirm != JOptionPane.YES_OPTION) return;

            // Criar aceitação
            SaleAcceptance acceptance = new SaleAcceptance(myUser, selectedProposal);
            
            // Enviar
            node.addTransaction(Utils.ObjectToBase64(acceptance));
            JOptionPane.showMessageDialog(this, "Negócio fechado! Aguarde a mineração.");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btAcceptActionPerformed

    private void btCreateProposalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateProposalActionPerformed
        // Abre a nova janela unificada de criação de propostas
        if (node != null) {
            new CreateProposalGUI(node, myUser).setVisible(true);
            // Podes fechar o mercado e obrigar a reabrir para atualizar, 
            // ou adicionar um listener para atualizar a tabela quando a outra fechar.
            // Para simplificar, deixamos esta janela aberta.
        }
    }//GEN-LAST:event_btCreateProposalActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAccept;
    private javax.swing.JButton btCreateProposal;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMarket;
    // End of variables declaration//GEN-END:variables
}
