/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain06_RealEstate;

/**
 *
 * @author Tiago Paiva
 */
public class MyPropertiesGUI extends javax.swing.JFrame {
    
    private RemoteNodeInterface node;
    private RealEstateUser myUser;
    private javax.swing.table.DefaultTableModel model;

    /**
     * Creates new form MyPropertiesGUI
     */
   public MyPropertiesGUI(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        
        initComponents();
        
        // Configurações visuais
        setLocationRelativeTo(null);
        setTitle("Carteira de Ativos - " + user.getUserName());
        
        // Preparar a tabela
        model = (javax.swing.table.DefaultTableModel) tblProperties.getModel();
        
        // Carregar dados automaticamente
        loadWallet();
    }
   
   private void loadWallet() {
        // 1. Limpar a tabela
        model.setRowCount(0);
        
        if (node == null) return;
        
        try {
            // 2. Mapa para guardar os saldos
            java.util.Map<String, Integer> wallet = new java.util.HashMap<>();
            
            // 3. Obter a Blockchain
            BlockChain bc = node.getBlockchain();
            java.util.List<Block> blockList = bc.getBlocks();
            
            // Variável para normalizar o nome do utilizador (remover espaços extra)
            String me = myUser.getUserName().trim();

            for (Block b : blockList) {
                // Obter transações
                java.util.List transactions = b.getTransactions(); 
                if (transactions == null) continue;

                for (Object rawObj : transactions) {
                    try {
                        Object txObj = rawObj;

                        // Conversão de Base64 se necessário
                        if (rawObj instanceof String) {
                            byte[] data = java.util.Base64.getDecoder().decode((String) rawObj);
                            try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(new java.io.ByteArrayInputStream(data))) {
                                txObj = ois.readObject();
                            }
                        }

                        if (txObj instanceof RealEstateTransaction) {
                            RealEstateTransaction tx = (RealEstateTransaction) txObj;
                            
                            String assetID = tx.getAssetName();
                            int amount = tx.getTokenAmount();
                            String sender = tx.getTxtSender().trim();
                            String receiver = tx.getTxtReceiver().trim();
                            
                            // --- LÓGICA DE CONTABILIDADE CORRIGIDA ---
                            
                            // 1. Se fui eu que recebi -> SOMA
                            if (receiver.equals(me)) {
                                int current = wallet.getOrDefault(assetID, 0);
                                wallet.put(assetID, current + amount);
                            }
                            
                            // 2. Se fui eu que enviei -> SUBTRAI
                            // FIX: Só subtraímos se enviarmos para OUTRA pessoa.
                            // Se sender == receiver, é um Registo (criação de dinheiro), logo não subtraímos.
                            if (sender.equals(me) && !sender.equals(receiver)) {
                                int current = wallet.getOrDefault(assetID, 0);
                                wallet.put(assetID, current - amount);
                            }
                        }
                    } catch (Exception e) {
                        // Ignorar erros de parse
                    }
                }
            }
            
            // 4. Preencher a tabela com saldos positivos
            for (java.util.Map.Entry<String, Integer> entry : wallet.entrySet()) {
                if (entry.getValue() > 0) {
                    model.addRow(new Object[]{
                        entry.getKey(),      // ID do Imóvel
                        entry.getValue(),    // Quantidade
                        "Propriedade RWA"
                    });
                }
            }
            
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProperties = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID do Imóvel", "Tokens Possuídos", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProperties);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(526, 50));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btRefresh.setText("atualizar");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(btRefresh)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btRefresh))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        loadWallet();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPropertiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPropertiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPropertiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPropertiesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProperties;
    // End of variables declaration//GEN-END:variables
}
