/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain06_RealEstate;


import javax.swing.JOptionPane;
import utils.RMI;

/**
 *
 * @author IPT
 */
public class MyService extends javax.swing.JFrame {
    
    // Variáveis para guardar a sessão
    private RemoteNodeInterface node;
    private RealEstateUser myUser;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(blockchain06_RealEstate.MyService.class.getName());
    /**
     * Construtor Obrigatório para o Login funcionar
     */
    public MyService(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        
        initComponents(); // Inicia o design gráfico
        
        // Configurações extra
        this.setLocationRelativeTo(null);
        this.setTitle("Dashboard - Utilizador: " + (user != null ? user.getUserName() : "Desconhecido"));
        
        if (user != null) {
            lblWelcome.setText("Bem vindo, " + user.getUserName());
        }
    }

    /**
     * Construtor vazio (necessário para o editor gráfico do NetBeans não dar erro)
     * Não deve ser usado pelo Login
     */
    public MyService() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNodeAddress = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        txtTransaction = new javax.swing.JTextField();
        btAddTransaction = new javax.swing.JButton();
        btRegisterProp = new javax.swing.JButton();
        btViewMyAssets = new javax.swing.JButton();
        btTenantArea = new javax.swing.JButton();
        btMarket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNodeAddress.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtNodeAddress.setText("//10.10.208.35:10010/remoteP2P");
        txtNodeAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote Object Address"));
        txtNodeAddress.addActionListener(this::txtNodeAddressActionPerformed);
        txtNodeAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNodeAddressKeyPressed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblWelcome.setText("Bem vindo, @user ");

        txtTransaction.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtTransaction.setText("Transaction 1");

        btAddTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/transaction.png"))); // NOI18N
        btAddTransaction.setText("Add Transaction");
        btAddTransaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAddTransaction.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btAddTransaction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAddTransaction.addActionListener(this::btAddTransactionActionPerformed);

        btRegisterProp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ic-register.png"))); // NOI18N
        btRegisterProp.setText("Registar propriedade");
        btRegisterProp.addActionListener(this::btRegisterPropActionPerformed);

        btViewMyAssets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ic-house.png"))); // NOI18N
        btViewMyAssets.setText("Ver Minhas Propriedades");
        btViewMyAssets.addActionListener(this::btViewMyAssetsActionPerformed);

        btTenantArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ic-rental.png"))); // NOI18N
        btTenantArea.setText("Área de Inquilino");
        btTenantArea.addActionListener(this::btTenantAreaActionPerformed);

        btMarket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ic-transfer.png"))); // NOI18N
        btMarket.setText("Mercado Imobiliário");
        btMarket.addActionListener(this::btMarketActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNodeAddress)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWelcome)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btMarket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btTenantArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRegisterProp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btViewMyAssets, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(33, 33, 33)
                .addComponent(btRegisterProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btViewMyAssets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTenantArea)
                .addGap(25, 25, 25)
                .addComponent(txtNodeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAddTransaction, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTransaction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNodeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodeAddressActionPerformed

    private void txtNodeAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNodeAddressKeyPressed
       
    }//GEN-LAST:event_txtNodeAddressKeyPressed

    private void btAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTransactionActionPerformed
        try {
            RemoteNodeInterface remote = (RemoteNodeInterface) RMI.getRemote(txtNodeAddress.getText());
            remote.addTransaction(txtTransaction.getText());
        } catch (Exception ex) {
            System.getLogger(MyService.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } 
        
    }//GEN-LAST:event_btAddTransactionActionPerformed

    private void btRegisterPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterPropActionPerformed
        // TODO add your handling code here:
        if (node == null || myUser == null) {
            JOptionPane.showMessageDialog(this, "Erro de conexão ou sessão inválida.");
            return;
        }
        
        // Abre a janela de registo passando as credenciais
        RegisterPropertyGUI regWin = new RegisterPropertyGUI(node, myUser);
        regWin.setVisible(true);
    }//GEN-LAST:event_btRegisterPropActionPerformed

    private void btTenantAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTenantAreaActionPerformed
        // TODO add your handling code here:
        if (node != null) {
            new TenantContractsGUI(node, myUser).setVisible(true);
        }
    }//GEN-LAST:event_btTenantAreaActionPerformed

    private void btViewMyAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btViewMyAssetsActionPerformed
        // TODO add your handling code here:
        if (node != null && myUser != null) {
            new MyPropertiesGUI(node, myUser).setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Sessão inválida.");
        }
    }//GEN-LAST:event_btViewMyAssetsActionPerformed

    private void btMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMarketActionPerformed
        // TODO add your handling code here:
        if (node != null) {
            // Abre a janela do Mercado passando a conexão e o utilizador atual
            new MarketplaceGUI(node, myUser).setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: Sem conexão ao servidor.");
        }
    }//GEN-LAST:event_btMarketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddTransaction;
    private javax.swing.JButton btMarket;
    private javax.swing.JButton btRegisterProp;
    private javax.swing.JButton btTenantArea;
    private javax.swing.JButton btViewMyAssets;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtNodeAddress;
    private javax.swing.JTextField txtTransaction;
    // End of variables declaration//GEN-END:variables
}
