/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain06_RealEstate;

/**
 *
 * @author Tiago Paiva
 */
public class RegisterPropertyGUI extends javax.swing.JFrame {

    // Referência para o nó da blockchain (Miner)
    RemoteNodeInterface node;
    RealEstateUser myUser;
    /**
     * Creates new form RegisterPropertyGUI
     */
    public RegisterPropertyGUI(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAddress = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAddress.setText("jTextField1");

        txtType.setText("jTextField2");

        txtArea.setText("jTextField3");

        txtValue.setText("jTextField4");

        btRegister.setText("jButton1");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegister)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btRegister)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(822, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
       
        try {
            // 1. Validar conexão e sessão
            if (node == null || myUser == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro Crítico: Sem dados de sessão ou conexão.");
                return;
            }

            // 2. Ler APENAS os dados do Imóvel (O dono é automático)
            String address = txtAddress.getText();
            String type = txtType.getText();

            if (txtArea.getText().isEmpty() || txtValue.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Preencha a Área e o Valor!");
                return;
            }

            double area = Double.parseDouble(txtArea.getText());
            double value = Double.parseDouble(txtValue.getText());

            // 3. Criar o Objeto Imóvel (Gera ID Hash automático)
            RealEstateProperty prop = new RealEstateProperty(address, type, area, value);
            String assetKey = prop.getUniqueBlockchainID();

            // 4. Criar a Transação usando o objeto USER (Sem password)
            // Lógica: O 'myUser' (Sender) envia para 'myUser.getName()' (Receiver)
            int genesisSupply = 1000;

            RealEstateTransaction tx = new RealEstateTransaction(
                myUser,               // OBJETO user autenticado (contém a PrivateKey para assinar)
                myUser.getUserName(), // Nome do destinatário (ele próprio)
                assetKey,             // ID do imóvel
                genesisSupply         // 1000 tokens
            );

            // 5. Enviar para a Blockchain
            node.addTransaction(utils.Utils.ObjectToBase64(tx));

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Imóvel Registado com Sucesso!\n\nID Gerado: " + assetKey, 
                "Sucesso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            this.dispose(); // Fecha a janela e volta ao Menu

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro no registo: " + ex.getMessage());
            ex.printStackTrace();
        }
    
    }//GEN-LAST:event_btRegisterActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
