/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain06_RealEstate;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Utils;

/**
 *
 * @author Tiago Paiva
 */
public class TenantContractsGUI extends javax.swing.JFrame {

    private RemoteNodeInterface node;
    private RealEstateUser myUser;
    private DefaultTableModel model;

    public TenantContractsGUI(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Meus Contratos de Arrendamento - " + user.getUserName());
        
        model = (DefaultTableModel) tblContracts.getModel();
        model.setColumnIdentifiers(new String[]{"ID Contrato", "Imóvel", "Valor (€)", "Estado"});
        
        loadContracts();
    }

    private void loadContracts() {
        // 1. Limpar a tabela
        model.setRowCount(0);
        
        if (node == null) return;

        try {
            // 2. Preparar listas
            java.util.List<RentalTransaction> myOffers = new java.util.ArrayList<>();
            java.util.Set<String> acceptedContractIDs = new java.util.HashSet<>();
            String myName = myUser.getUserName().trim(); // Trim para evitar erros de espaços

            // 3. Obter a Blockchain
            BlockChain bc = node.getBlockchain();
            java.util.List<Block> blocks = bc.getBlocks(); // CORREÇÃO: getBlocks()

            // 4. Varrer a Blockchain
            for (Block b : blocks) {
                java.util.List transactions = b.getTransactions(); // CORREÇÃO: getTransactions()
                
                if (transactions == null) continue;

                for (Object rawObj : transactions) {
                    try {
                        Object decoded = rawObj;

                        // Descodificar Base64 manualmente (para garantir que funciona sem utils externos)
                        if (rawObj instanceof String) {
                            byte[] data = java.util.Base64.getDecoder().decode((String) rawObj);
                            try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(new java.io.ByteArrayInputStream(data))) {
                                decoded = ois.readObject();
                            }
                        }

                        // --- VERIFICAR SE É UMA PROPOSTA PARA MIM ---
                        if (decoded instanceof RentalTransaction) {
                            RentalTransaction tx = (RentalTransaction) decoded;
                            // Se o nome do inquilino for igual ao meu
                            if (tx.getTenantName().trim().equals(myName)) {
                                myOffers.add(tx);
                            }
                        }
                        
                        // --- VERIFICAR SE EU JÁ ACEITEI ---
                        else if (decoded instanceof RentalAcceptanceTransaction) {
                            RentalAcceptanceTransaction tx = (RentalAcceptanceTransaction) decoded;
                            // Se fui eu que aceitei
                            if (tx.getTenantName().trim().equals(myName)) {
                                acceptedContractIDs.add(tx.getContractID());
                            }
                        }
                        
                    } catch (Exception e) {
                        // Ignorar transações que não sejam legíveis ou de outros tipos
                    }
                }
            }

            // 5. Preencher a tabela cruzando os dados
            for (RentalTransaction offer : myOffers) {
                String status = "PENDENTE";
                
                // Se o ID deste contrato estiver na lista de aceites
                if (acceptedContractIDs.contains(offer.getContractID())) {
                    status = "ATIVO (Assinado)";
                }

                model.addRow(new Object[]{
                    offer.getContractID(),
                    offer.getPropertyID(),
                    offer.getRentValue() + " €",
                    status
                });
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar contratos: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContracts = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btClose = new javax.swing.JButton();
        btSignContract = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblContracts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Contrato", "Imóvel", "Valor", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblContracts);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btClose.setText("Fechar");
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        btSignContract.setText("Assinar Contrato");
        btSignContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignContractActionPerformed(evt);
            }
        });

        btRefresh.setText("Atualizar");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(btSignContract)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClose)
                    .addComponent(btRefresh)
                    .addComponent(btSignContract))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSignContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignContractActionPerformed
        // TODO add your handling code here:
        int row = tblContracts.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um contrato pendente.");
            return;
        }

        String status = (String) model.getValueAt(row, 3);
        if (!status.equals("PENDENTE")) {
            JOptionPane.showMessageDialog(this, "Este contrato já está assinado!");
            return;
        }

        String contractID = (String) model.getValueAt(row, 0);

        try {
            // Confirmar com o utilizador
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Deseja assinar digitalmente este contrato?\nEsta ação é irreversível na Blockchain.", 
                    "Assinar Contrato", JOptionPane.YES_NO_OPTION);
            
            if (confirm != JOptionPane.YES_OPTION) return;

            // Criar a transação de Aceitação
            RentalAcceptanceTransaction acceptance = new RentalAcceptanceTransaction(myUser, contractID);

            // Enviar para a rede
            node.addTransaction(Utils.ObjectToBase64(acceptance));

            JOptionPane.showMessageDialog(this, "Contrato assinado e enviado para a Blockchain!");
            loadContracts(); // Atualizar tabela

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao assinar: " + e.getMessage());
        }
    }//GEN-LAST:event_btSignContractActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        // TODO add your handling code here:
        loadContracts();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSignContract;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContracts;
    // End of variables declaration//GEN-END:variables
}
