/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blockchain06_RealEstate;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Utils;

/**
 *
 * @author Tiago Paiva
 */
public class TenantContractsGUI extends javax.swing.JFrame {

    private RemoteNodeInterface node;
    private RealEstateUser myUser;
    private DefaultTableModel model;

    public TenantContractsGUI(RemoteNodeInterface node, RealEstateUser user) {
        this.node = node;
        this.myUser = user;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Meus Contratos de Arrendamento - " + user.getUserName());
        
        model = (DefaultTableModel) tblContracts.getModel();
        model.setColumnIdentifiers(new String[]{"ID Contrato", "Imóvel", "Valor (€)", "Estado"});
        
        loadContracts();
    }

    private void loadContracts() {
        model.setRowCount(0);
        if (node == null) return;

        try {
            BlockChain bc = node.getBlockchain();
            
            // Listas temporárias
            List<RentalTransaction> myOffers = new ArrayList<>();
            Set<String> acceptedContractIDs = new HashSet<>();

            // 1. Varrer a Blockchain
            for (Block b : bc.getChain()) {
                for (Object txObj : b.getData()) {
                    try {
                        Object decoded = (txObj instanceof String) ? Utils.StringToObject((String)txObj) : txObj;

                        // Se for uma OFERTA dirigida a mim
                        if (decoded instanceof RentalTransaction) {
                            RentalTransaction tx = (RentalTransaction) decoded;
                            if (tx.getTenantName().equals(myUser.getUserName())) {
                                myOffers.add(tx);
                            }
                        }
                        
                        // Se for uma ACEITAÇÃO minha
                        if (decoded instanceof RentalAcceptanceTransaction) {
                            RentalAcceptanceTransaction tx = (RentalAcceptanceTransaction) decoded;
                            if (tx.getTenantName().equals(myUser.getUserName())) {
                                acceptedContractIDs.add(tx.getContractID());
                            }
                        }
                        
                    } catch (Exception e) {}
                }
            }

            // 2. Preencher a tabela cruzando os dados
            for (RentalTransaction offer : myOffers) {
                String status = "PENDENTE";
                if (acceptedContractIDs.contains(offer.getContractID())) {
                    status = "ATIVO (Assinado)";
                }

                model.addRow(new Object[]{
                    offer.getContractID(),
                    offer.getPropertyID(),
                    offer.getRentValue(),
                    status
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContracts = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btRefresh = new javax.swing.JButton();
        btSignContract = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblContracts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Contrato", "Imóvel", "Valor", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblContracts);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btRefresh.setText("Atualizar");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        btSignContract.setText("Assinar Contrato");
        btSignContract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignContractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btRefresh)
                .addGap(83, 83, 83)
                .addComponent(btSignContract)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRefresh)
                    .addComponent(btSignContract))
                .addGap(36, 36, 36))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSignContractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignContractActionPerformed
        // TODO add your handling code here:
        int row = tblContracts.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um contrato pendente.");
            return;
        }

        String status = (String) model.getValueAt(row, 3);
        if (!status.equals("PENDENTE")) {
            JOptionPane.showMessageDialog(this, "Este contrato já está assinado!");
            return;
        }

        String contractID = (String) model.getValueAt(row, 0);

        try {
            // Confirmar com o utilizador
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Deseja assinar digitalmente este contrato?\nEsta ação é irreversível na Blockchain.", 
                    "Assinar Contrato", JOptionPane.YES_NO_OPTION);
            
            if (confirm != JOptionPane.YES_OPTION) return;

            // Criar a transação de Aceitação
            RentalAcceptanceTransaction acceptance = new RentalAcceptanceTransaction(myUser, contractID);

            // Enviar para a rede
            node.addTransaction(Utils.ObjectToBase64(acceptance));

            JOptionPane.showMessageDialog(this, "Contrato assinado e enviado para a Blockchain!");
            loadContracts(); // Atualizar tabela

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao assinar: " + e.getMessage());
        }
    }//GEN-LAST:event_btSignContractActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        // TODO add your handling code here:
        loadContracts();
    }//GEN-LAST:event_btRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenantContractsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenantContractsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenantContractsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenantContractsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TenantContractsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSignContract;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblContracts;
    // End of variables declaration//GEN-END:variables
}
